### ISSUE TITLE
matlabbatch{4}.spm.spatial.coreg.estwrite.ref(1) does not allow to work in the script

### ISSUE THREAD

**Issue by JXXCgit** [andrewjahn/SPM_Scripts#1]
Hi, Dear Andrew, 
Thank you for offering the script. Here i have a question to ask about the SPM script_'RunPreproc_1stLevel_job.m'.
This script  can work properly on the batch but not when trying to run it through the script. 
the error at the command: matlabbatch{4}.spm.spatial.coreg.estwrite.ref(1) = cfg_dep('Realign: Estimate & Reslice: Mean Image', substruct('.','val', '{}',{2}, '.','val', '{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','rmean'));

the error indicate that: Unable to perform assignment because value of type 'cfg_dep' is not convertible to 'char'.

Error in RunPreproc_1stLevel_job (line 57)
matlabbatch{4}.spm.spatial.coreg.estwrite.ref(1) = cfg_dep('Realign: Estimate & Reslice: Mean Image', substruct('.','val', '{}',{2}, '.','val',
'{}',{1}, '.','val', '{}',{1}, '.','val', '{}',{1}), substruct('.','rmean'));
Caused by:
Error using char
Conversion to char from cfg_dep is not possible.

do you have such issue before?
thank you for tips
greetings
xiu

**Comment by andrewjahn** [comment]
Hi Xiu,

Thanks for getting in touch! Unfortunately, I haven't seen that particular
error before; have you tried loading the globals from the command line
first, by typing "spm global"? Also, what version of Matlab are you using?
Either you might have to update your Matlab to 2019 or later, or I need to
update my scripts.


Best,

-Andy
